[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/public/sandbox/index.html"
  status = 200

[[redirects]]
  from = "/sandbox"  
  to = "/public/sandbox/index.html"
  status = 200

[[redirects]]
  from = "/client_account"
  to = "/public/sandbox/index.html"
  status = 200

[[redirects]]
  from = "/api/v1/verify"
  to = "/.netlify/functions/verify"
  status = 200

# Add employment verification function routes
[[redirects]]
  from = "/employment-verify"
  to = "/.netlify/functions/employment-verify"
  status = 200

[[redirects]]
  from = "/employment-verify/*"
  to = "/.netlify/functions/employment-verify"
  status = 200
