cat > netlify.toml << 'EOF'
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Main site redirects
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sandbox"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/client_account"
  to = "/index.html"
  status = 200

# API redirects
[[redirects]]
  from = "/api/v1/verify"
  to = "/.netlify/functions/verify"
  status = 200

# Employment verification API routes
[[redirects]]
  from = "/employment-verify/*"
  to = "/.netlify/functions/employment-verify/:splat"
  status = 200

# Sandbox subdomain serving
[[redirects]]
  from = "/*"
  to = "/sandbox-interface.html"
  status = 200
  conditions = {Host = ["sandbox.moderntax.io"]}
EOF
