[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Route for employment verification page
[[redirects]]
  from = "/employment-verification"
  to = "/employment-verification.html"
  status = 200

# API routes remain unchanged
[[redirects]]
  from = "/api/v1/verify"
  to = "/.netlify/functions/verify"
  status = 200

[[redirects]]
  from = "/employment-verify/*"
  to = "/.netlify/functions/employment-verify/:splat"
  status = 200
